
class Sensor:
    __doc__ = 'Simple Sensor Class'
    
    def __init__(self, ra, acc, sid, **kwargs):
        super().__init__(**kwargs)
        self._range = ra
        self._accuracy = acc
        self._sensor_id = sid
        
    def get_range(self):
        return self._range
            
    def get_id(self):
        return self._sensor_id
    
class InfraRedSensor(Sensor):
    __doc__ = 'Infra Red Sensor Class'
    
    def __init__(self, mot, ty, **kwargs):
        super().__init__(**kwargs)
        self._max_op_temp = mot
        self._type = ty
        
    def get_type(self):
        return self._type
        
    def detect_motion(self):
        # Simulating a motion detection event generated by the sensor
        return True
    
class UltraSonicSensor(Sensor):
    __doc__ = 'Ultra Sonic Sensor Class'
    
    def __init__(self, freq, **kwargs):
        super().__init__(**kwargs)
        self._operating_freq = freq
        
    def get_distance(self):
        # Simulating a distance measured by the sensor (in cm)
        return 75

    
class SmartBin():
    __doc__ = 'SmartBin Class'
    
    """Represent smart bin using has-a relations"""
    
    def __init__(self, cap, irs, uss, **kwargs):
        super().__init__(**kwargs)
        self._ultraSonicSensor = uss
        self._infraRedSensor = irs
        self._capacity = cap
        self._fill_level = 0

    def get_capacity(self):
        return self._capacity
        
    def get_fill_level(self):
        return self._fill_level
        
    def update_fill_level(self):
        """ Computes the amount of available space in the bin."""
        # We assume here that an empty bin will have 100cm of free space
        # between the bin lid and the bottom when empty.
        self._fill_level = (100 - self._ultraSonicSensor.get_distance()) / 100

infSens = InfraRedSensor(mot = 30, ty = 'Passive', ra=300, acc=1.0, sid = 'abc1234')   
ultSens = UltraSonicSensor(freq = 400.2, ra = 10, acc = 1.0, sid = 'cdef124')
smartBin = SmartBin(cap = 500, irs = infSens, uss = ultSens)
# mysens1 = SmartBin(cap=500,freq=400.2,mot=30,ty='Passive',ra=300,acc=1.0,sid='abc1234')
print(smartBin.get_capacity())
print(smartBin.get_fill_level())
smartBin.update_fill_level()
print(smartBin.get_fill_level())